### ISSUE TITLE
源码启动 报错少了oss的表

### ISSUE THREAD

**Issue by xiaoxiafeng** [LiuYuYang01/ThriveX-Server#17]
Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'blog.oss' doesn't exist
ThriveX.sql里面没有oss的表结构

**Comment by LiuYuYang01** [comment]
不好意思忘记加了，这几天太忙了，我有时间修复一下

**Comment by LiuYuYang01** [comment]
可以加个微信liuyuyang2023

**Comment by xiaoxiafeng** [comment]
加了。
找到oss表结构，数据库补完就成功的运行起来了

**Comment by LiuYuYang01** [comment]
OK
