### ISSUE TITLE
文章删除后任能看见

### ISSUE THREAD

**Issue by JayFans2000** [LiuYuYang01/ThriveX-Server#19]
1. 文章删除放回收站后，前端用户能在下一页中看见该文章。
![image](https://github.com/user-attachments/assets/96338af9-316c-445b-abd7-88cc5a53b251)

2. 访问已删除的文章id任能正常访问，如：https://域名/article/{被删除的文章id}

**Comment by LiuYuYang01** [comment]
已解决
